### ISSUE TITLE
Pre create shell profiles 

### ISSUE THREAD

**Issue by ihardy** [WRLC/ORCID-Create-on-demand#11]
Use this to test updating a record by enhancing it w/ORCID

**Comment by ihardy** [comment]
Aaron, Gwendolyn, Stefan

**Comment by krebeck** [comment]
Completed http://auislandora-dev.wrlc.org/islandora/object/ir%3Abios

**Comment by dongourley** [comment]
Why do some of these profiles show Identifier (e.g. Stefan, Susan) and others don't (e.g. Aaron, Gwendolyn) ?

Anyway, can you send me one of the MADS documents in XML? If the Identifier is in some MADS and not others, pls send one that has it (Stefan or Susan). I want to use the same MADS field/tag names in the JSON stream that I send @ihardy for #14.

**Comment by krebeck** [comment]
The Identifier field is suppressed if it's null.  I didn't put an
identifier in my MADS (or Gwendolyn's) yet, because I didn't want to mess
up the testing with dirty data.

The MADS from Stefan's full record is attached.  I'm also including a
default thumbnail object that we can include for every newly created person
object.  The REST command for adding a thumbnail should be in my solution
for the API command issue.

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040
